------------------------------------/register 2024/2/5 11:10:13------------------------------------

TypeORMError: Cannot update entity because entity id is not set in the entity.
    at C:\Users\dell\Desktop\platesharee\Backend\src\query-builder\ReturningResultsEntityUpdator.ts:217:27
    at Array.map (<anonymous>)
    at ReturningResultsEntityUpdator.insert (C:\Users\dell\Desktop\platesharee\Backend\src\query-builder\ReturningResultsEntityUpdator.ts:210:40)
    at InsertQueryBuilder.execute (C:\Users\dell\Desktop\platesharee\Backend\src\query-builder\InsertQueryBuilder.ts:175:53)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

----------------------------------------------------------------------------------------------------

--------------------------------------/login 2024/2/0 10:25:38--------------------------------------

TypeError: Cannot read properties of undefined (reading 'email')
    at AuthService.<anonymous> (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:40:78)
    at step (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:33:23)
    at Object.next (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:14:53)
    at C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:4:12)
    at AuthService.login (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:83:16)
    at AuthController.login (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\auth.controller.ts:24:34)
    at AuthController.<anonymous> (C:\Users\dell\Desktop\platesharee\Backend\src\lib\bind.ts:116:46)
    at step (C:\Users\dell\Desktop\platesharee\Backend\src\lib\bind.ts:33:23)

----------------------------------------------------------------------------------------------------

-----------------------------------/authorized 2024/2/0 10:43:14-----------------------------------

JsonWebTokenError: invalid signature
    at C:\Users\dell\Desktop\platesharee\Backend\node_modules\jsonwebtoken\verify.js:171:19
    at getSecret (C:\Users\dell\Desktop\platesharee\Backend\node_modules\jsonwebtoken\verify.js:97:14)
    at Object.module.exports [as verify] (C:\Users\dell\Desktop\platesharee\Backend\node_modules\jsonwebtoken\verify.js:101:10)
    at GlobalStore._validate_token (C:\Users\dell\Desktop\platesharee\Backend\src\store\store.global.ts:26:26)
    at GlobalStore.verify_login_token (C:\Users\dell\Desktop\platesharee\Backend\src\store\store.global.ts:70:25)
    at AuthController.<anonymous> (C:\Users\dell\Desktop\platesharee\Backend\src\guards\role.guard.ts:15:45)
    at step (C:\Users\dell\Desktop\platesharee\Backend\src\guards\role.guard.ts:33:23)
    at Object.next (C:\Users\dell\Desktop\platesharee\Backend\src\guards\role.guard.ts:14:53)
    at C:\Users\dell\Desktop\platesharee\Backend\src\guards\role.guard.ts:8:71
    at new Promise (<anonymous>)

----------------------------------------------------------------------------------------------------

------------------------------------/authorized 2024/2/0 10:44:1------------------------------------

JsonWebTokenError: invalid signature
    at C:\Users\dell\Desktop\platesharee\Backend\node_modules\jsonwebtoken\verify.js:171:19
    at getSecret (C:\Users\dell\Desktop\platesharee\Backend\node_modules\jsonwebtoken\verify.js:97:14)
    at Object.module.exports [as verify] (C:\Users\dell\Desktop\platesharee\Backend\node_modules\jsonwebtoken\verify.js:101:10)
    at GlobalStore._validate_token (C:\Users\dell\Desktop\platesharee\Backend\src\store\store.global.ts:26:26)
    at GlobalStore.verify_login_token (C:\Users\dell\Desktop\platesharee\Backend\src\store\store.global.ts:70:25)
    at AuthController.<anonymous> (C:\Users\dell\Desktop\platesharee\Backend\src\guards\role.guard.ts:15:45)
    at step (C:\Users\dell\Desktop\platesharee\Backend\src\guards\role.guard.ts:33:23)
    at Object.next (C:\Users\dell\Desktop\platesharee\Backend\src\guards\role.guard.ts:14:53)
    at C:\Users\dell\Desktop\platesharee\Backend\src\guards\role.guard.ts:8:71
    at new Promise (<anonymous>)

----------------------------------------------------------------------------------------------------

------------------------------------/authorized 2024/2/0 10:44:9------------------------------------

JsonWebTokenError: invalid signature
    at C:\Users\dell\Desktop\platesharee\Backend\node_modules\jsonwebtoken\verify.js:171:19
    at getSecret (C:\Users\dell\Desktop\platesharee\Backend\node_modules\jsonwebtoken\verify.js:97:14)
    at Object.module.exports [as verify] (C:\Users\dell\Desktop\platesharee\Backend\node_modules\jsonwebtoken\verify.js:101:10)
    at GlobalStore._validate_token (C:\Users\dell\Desktop\platesharee\Backend\src\store\store.global.ts:26:26)
    at GlobalStore.verify_login_token (C:\Users\dell\Desktop\platesharee\Backend\src\store\store.global.ts:70:25)
    at AuthController.<anonymous> (C:\Users\dell\Desktop\platesharee\Backend\src\guards\role.guard.ts:15:45)
    at step (C:\Users\dell\Desktop\platesharee\Backend\src\guards\role.guard.ts:33:23)
    at Object.next (C:\Users\dell\Desktop\platesharee\Backend\src\guards\role.guard.ts:14:53)
    at C:\Users\dell\Desktop\platesharee\Backend\src\guards\role.guard.ts:8:71
    at new Promise (<anonymous>)

----------------------------------------------------------------------------------------------------

-------------------------------------/login/ 2024/2/5 11:10:41-------------------------------------

Error: data and hash arguments required
    at Object.compareSync (C:\Users\dell\Desktop\platesharee\Backend\node_modules\bcrypt\bcrypt.js:166:15)
    at verifyHash (C:\Users\dell\Desktop\platesharee\Backend\src\utils\base.util.ts:39:19)
    at AuthService.<anonymous> (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:40:24)
    at step (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:33:23)
    at Object.next (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:14:53)
    at fulfilled (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

----------------------------------------------------------------------------------------------------

-------------------------------------/login/ 2024/2/5 11:11:35-------------------------------------

Error: data and hash arguments required
    at Object.compareSync (C:\Users\dell\Desktop\platesharee\Backend\node_modules\bcrypt\bcrypt.js:166:15)
    at verifyHash (C:\Users\dell\Desktop\platesharee\Backend\src\utils\base.util.ts:39:19)
    at AuthService.<anonymous> (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:40:24)
    at step (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:33:23)
    at Object.next (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:14:53)
    at fulfilled (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

----------------------------------------------------------------------------------------------------

-------------------------------------/login/ 2024/2/5 11:40:59-------------------------------------

Error: data and hash arguments required
    at Object.compareSync (C:\Users\dell\Desktop\platesharee\Backend\node_modules\bcrypt\bcrypt.js:166:15)
    at verifyHash (C:\Users\dell\Desktop\platesharee\Backend\src\utils\base.util.ts:39:19)
    at AuthService.<anonymous> (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:40:24)
    at step (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:33:23)
    at Object.next (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:14:53)
    at fulfilled (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

----------------------------------------------------------------------------------------------------

--------------------------------------/login/ 2024/2/5 11:43:7--------------------------------------

Error: data and hash arguments required
    at Object.compareSync (C:\Users\dell\Desktop\platesharee\Backend\node_modules\bcrypt\bcrypt.js:166:15)
    at verifyHash (C:\Users\dell\Desktop\platesharee\Backend\src\utils\base.util.ts:39:19)
    at AuthService.<anonymous> (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:40:24)
    at step (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:33:23)
    at Object.next (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:14:53)
    at fulfilled (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

----------------------------------------------------------------------------------------------------

-------------------------------------/login/ 2024/2/5 11:43:46-------------------------------------

Error: data and hash arguments required
    at Object.compareSync (C:\Users\dell\Desktop\platesharee\Backend\node_modules\bcrypt\bcrypt.js:166:15)
    at verifyHash (C:\Users\dell\Desktop\platesharee\Backend\src\utils\base.util.ts:39:19)
    at AuthService.<anonymous> (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:40:24)
    at step (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:33:23)
    at Object.next (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:14:53)
    at fulfilled (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

----------------------------------------------------------------------------------------------------

-------------------------------------/login/ 2024/2/5 11:44:28-------------------------------------

Error: data and hash arguments required
    at Object.compareSync (C:\Users\dell\Desktop\platesharee\Backend\node_modules\bcrypt\bcrypt.js:166:15)
    at verifyHash (C:\Users\dell\Desktop\platesharee\Backend\src\utils\base.util.ts:39:19)
    at AuthService.<anonymous> (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:40:24)
    at step (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:33:23)
    at Object.next (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:14:53)
    at fulfilled (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

----------------------------------------------------------------------------------------------------

-------------------------------------/login/ 2024/2/5 11:45:47-------------------------------------

Error: data and hash arguments required
    at Object.compareSync (C:\Users\dell\Desktop\platesharee\Backend\node_modules\bcrypt\bcrypt.js:166:15)
    at verifyHash (C:\Users\dell\Desktop\platesharee\Backend\src\utils\base.util.ts:39:19)
    at AuthService.<anonymous> (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:40:24)
    at step (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:33:23)
    at Object.next (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:14:53)
    at fulfilled (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

----------------------------------------------------------------------------------------------------

-------------------------------------/login/ 2024/2/5 11:52:15-------------------------------------

Error: data and hash arguments required
    at Object.compareSync (C:\Users\dell\Desktop\platesharee\Backend\node_modules\bcrypt\bcrypt.js:166:15)
    at verifyHash (C:\Users\dell\Desktop\platesharee\Backend\src\utils\base.util.ts:39:19)
    at AuthService.<anonymous> (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:40:24)
    at step (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:33:23)
    at Object.next (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:14:53)
    at fulfilled (C:\Users\dell\Desktop\platesharee\Backend\src\routes\auth\authservice.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

----------------------------------------------------------------------------------------------------

-----------------------------------/delete_post 2024/3/6 11:23:14-----------------------------------

SubjectWithoutIdentifierError: Internal error. Subject post must have an identifier to perform operation.
    at C:\Users\dell\Desktop\platesharee\Backend\src\persistence\SubjectExecutor.ts:689:27
    at Array.map (<anonymous>)
    at SubjectExecutor.executeRemoveOperations (C:\Users\dell\Desktop\platesharee\Backend\src\persistence\SubjectExecutor.ts:687:41)
    at SubjectExecutor.execute (C:\Users\dell\Desktop\platesharee\Backend\src\persistence\SubjectExecutor.ts:156:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at EntityPersistExecutor.execute (C:\Users\dell\Desktop\platesharee\Backend\src\persistence\EntityPersistExecutor.ts:182:21)

----------------------------------------------------------------------------------------------------

-----------------------------------/create_menu 2024/3/4 21:1:57-----------------------------------

Error: MimeType or size doesn't match
    at new FileSizeExceed (C:\Users\dell\Desktop\platesharee\Backend\src\middleware\error.middleware.ts:57:14)
    at FileStream.<anonymous> (C:\Users\dell\Desktop\platesharee\Backend\src\lib\imageHandler.ts:157:43)
    at FileStream.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

----------------------------------------------------------------------------------------------------

-----------------------------------/create_menu 2024/3/4 21:2:26-----------------------------------

Error: MimeType or size doesn't match
    at new FileSizeExceed (C:\Users\dell\Desktop\platesharee\Backend\src\middleware\error.middleware.ts:57:14)
    at FileStream.<anonymous> (C:\Users\dell\Desktop\platesharee\Backend\src\lib\imageHandler.ts:157:43)
    at FileStream.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

----------------------------------------------------------------------------------------------------

-----------------------------------/create_menu 2024/3/4 21:2:29-----------------------------------

Error: MimeType or size doesn't match
    at new FileSizeExceed (C:\Users\dell\Desktop\platesharee\Backend\src\middleware\error.middleware.ts:57:14)
    at FileStream.<anonymous> (C:\Users\dell\Desktop\platesharee\Backend\src\lib\imageHandler.ts:157:43)
    at FileStream.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

----------------------------------------------------------------------------------------------------

------------------------------------/create_menu 2024/3/0 1:6:12------------------------------------

QueryFailedError: Unknown column 'NaN' in 'field list'
    at Query.onResult (C:\Users\dell\Desktop\platesharee\Backend\src\driver\mysql\MysqlQueryRunner.ts:246:33)
    at Query.execute (C:\Users\dell\Desktop\platesharee\Backend\node_modules\mysql2\lib\commands\command.js:36:14)
    at PoolConnection.handlePacket (C:\Users\dell\Desktop\platesharee\Backend\node_modules\mysql2\lib\connection.js:481:34)
    at PacketParser.onPacket (C:\Users\dell\Desktop\platesharee\Backend\node_modules\mysql2\lib\connection.js:97:12)
    at PacketParser.executeStart (C:\Users\dell\Desktop\platesharee\Backend\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Users\dell\Desktop\platesharee\Backend\node_modules\mysql2\lib\connection.js:104:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

------------------------------------/create_menu 2024/3/0 1:9:23------------------------------------

QueryFailedError: Unknown column 'NaN' in 'field list'
    at Query.onResult (C:\Users\dell\Desktop\platesharee\Backend\src\driver\mysql\MysqlQueryRunner.ts:246:33)
    at Query.execute (C:\Users\dell\Desktop\platesharee\Backend\node_modules\mysql2\lib\commands\command.js:36:14)
    at PoolConnection.handlePacket (C:\Users\dell\Desktop\platesharee\Backend\node_modules\mysql2\lib\connection.js:481:34)
    at PacketParser.onPacket (C:\Users\dell\Desktop\platesharee\Backend\node_modules\mysql2\lib\connection.js:97:12)
    at PacketParser.executeStart (C:\Users\dell\Desktop\platesharee\Backend\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Users\dell\Desktop\platesharee\Backend\node_modules\mysql2\lib\connection.js:104:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

-----------------------------------/create_menu 2024/3/0 10:53:5-----------------------------------

Error: MimeType or size doesn't match
    at new FileSizeExceed (C:\Users\dell\Desktop\platesharee\Backend\src\middleware\error.middleware.ts:57:14)
    at FileStream.<anonymous> (C:\Users\dell\Desktop\platesharee\Backend\src\lib\imageHandler.ts:157:43)
    at FileStream.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

----------------------------------------------------------------------------------------------------

-----------------------------------/create_event 2024/3/3 22:32:9-----------------------------------

Error: Multipart: Boundary not found
    at new Multipart (C:\Users\dell\Desktop\platesharee\Backend\node_modules\busboy\lib\types\multipart.js:233:13)
    at getInstance (C:\Users\dell\Desktop\platesharee\Backend\node_modules\busboy\lib\index.js:33:12)
    at module.exports (C:\Users\dell\Desktop\platesharee\Backend\node_modules\busboy\lib\index.js:56:10)
    at C:\Users\dell\Desktop\platesharee\Backend\src\lib\imageHandler.ts:146:30
    at new Promise (<anonymous>)
    at ImageHandler.requestImageHandler (C:\Users\dell\Desktop\platesharee\Backend\src\lib\imageHandler.ts:142:16)
    at ImageHandler.singleImage (C:\Users\dell\Desktop\platesharee\Backend\src\lib\imageHandler.ts:54:21)
    at EventController.<anonymous> (C:\Users\dell\Desktop\platesharee\Backend\src\lib\imageHandler.ts:206:43)
    at step (C:\Users\dell\Desktop\platesharee\Backend\src\lib\imageHandler.ts:65:23)
    at Object.next (C:\Users\dell\Desktop\platesharee\Backend\src\lib\imageHandler.ts:46:53)

----------------------------------------------------------------------------------------------------

----------------------------------/create_event 2024/3/3 22:36:22----------------------------------

Error: Multipart: Boundary not found
    at new Multipart (C:\Users\dell\Desktop\platesharee\Backend\node_modules\busboy\lib\types\multipart.js:233:13)
    at getInstance (C:\Users\dell\Desktop\platesharee\Backend\node_modules\busboy\lib\index.js:33:12)
    at module.exports (C:\Users\dell\Desktop\platesharee\Backend\node_modules\busboy\lib\index.js:56:10)
    at C:\Users\dell\Desktop\platesharee\Backend\src\lib\imageHandler.ts:146:30
    at new Promise (<anonymous>)
    at ImageHandler.requestImageHandler (C:\Users\dell\Desktop\platesharee\Backend\src\lib\imageHandler.ts:142:16)
    at ImageHandler.singleImage (C:\Users\dell\Desktop\platesharee\Backend\src\lib\imageHandler.ts:54:21)
    at EventController.<anonymous> (C:\Users\dell\Desktop\platesharee\Backend\src\lib\imageHandler.ts:206:43)
    at step (C:\Users\dell\Desktop\platesharee\Backend\src\lib\imageHandler.ts:65:23)
    at Object.next (C:\Users\dell\Desktop\platesharee\Backend\src\lib\imageHandler.ts:46:53)

----------------------------------------------------------------------------------------------------

-----------------------------------/create_event 2024/3/4 9:59:12-----------------------------------

Error: Multipart: Boundary not found
    at new Multipart (C:\Users\dell\Desktop\platesharee\Backend\node_modules\busboy\lib\types\multipart.js:233:13)
    at getInstance (C:\Users\dell\Desktop\platesharee\Backend\node_modules\busboy\lib\index.js:33:12)
    at module.exports (C:\Users\dell\Desktop\platesharee\Backend\node_modules\busboy\lib\index.js:56:10)
    at C:\Users\dell\Desktop\platesharee\Backend\src\lib\imageHandler.ts:146:30
    at new Promise (<anonymous>)
    at ImageHandler.requestImageHandler (C:\Users\dell\Desktop\platesharee\Backend\src\lib\imageHandler.ts:142:16)
    at ImageHandler.singleImage (C:\Users\dell\Desktop\platesharee\Backend\src\lib\imageHandler.ts:54:21)
    at EventController.<anonymous> (C:\Users\dell\Desktop\platesharee\Backend\src\lib\imageHandler.ts:206:43)
    at step (C:\Users\dell\Desktop\platesharee\Backend\src\lib\imageHandler.ts:65:23)
    at Object.next (C:\Users\dell\Desktop\platesharee\Backend\src\lib\imageHandler.ts:46:53)

----------------------------------------------------------------------------------------------------

-----------------------------------/create_event 2024/3/4 10:0:56-----------------------------------

Error: Multipart: Boundary not found
    at new Multipart (C:\Users\dell\Desktop\platesharee\Backend\node_modules\busboy\lib\types\multipart.js:233:13)
    at getInstance (C:\Users\dell\Desktop\platesharee\Backend\node_modules\busboy\lib\index.js:33:12)
    at module.exports (C:\Users\dell\Desktop\platesharee\Backend\node_modules\busboy\lib\index.js:56:10)
    at C:\Users\dell\Desktop\platesharee\Backend\src\lib\imageHandler.ts:146:30
    at new Promise (<anonymous>)
    at ImageHandler.requestImageHandler (C:\Users\dell\Desktop\platesharee\Backend\src\lib\imageHandler.ts:142:16)
    at ImageHandler.singleImage (C:\Users\dell\Desktop\platesharee\Backend\src\lib\imageHandler.ts:54:21)
    at EventController.<anonymous> (C:\Users\dell\Desktop\platesharee\Backend\src\lib\imageHandler.ts:206:43)
    at step (C:\Users\dell\Desktop\platesharee\Backend\src\lib\imageHandler.ts:65:23)
    at Object.next (C:\Users\dell\Desktop\platesharee\Backend\src\lib\imageHandler.ts:46:53)

----------------------------------------------------------------------------------------------------

-----------------------------------/create_menu 2024/3/5 10:53:52-----------------------------------

Error: MimeType or size doesn't match
    at new FileSizeExceed (/Users/sarbagyashahi/fyp/plateshare/Backend/src/middleware/error.middleware.ts:57:14)
    at FileStream.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/src/lib/imageHandler.ts:157:43)
    at FileStream.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

----------------------------------------------------------------------------------------------------

----------------------------------/create_event 2024/3/5 11:13:51----------------------------------

QueryFailedError: Field 'event_name' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

-----------------------------------/create_event 2024/3/5 11:14:0-----------------------------------

QueryFailedError: Field 'event_location' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

----------------------------------/create_event 2024/3/5 11:14:12----------------------------------

QueryFailedError: Field 'event_time' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

----------------------------------/create_event 2024/3/5 11:14:21----------------------------------

QueryFailedError: Out of range value for column 'event_time' at row 1
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

----------------------------------/create_event 2024/3/5 11:14:25----------------------------------

QueryFailedError: Incorrect integer value: 'asdsad' for column `plateshare`.`event`.`event_time` at row 1
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

-----------------------------------/create_event 2024/3/5 11:15:1-----------------------------------

QueryFailedError: Field 'event_description' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

-----------------------------------/create_post 2024/3/5 12:23:41-----------------------------------

QueryFailedError: Field 'post_name' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

-----------------------------------/create_post 2024/3/5 12:24:26-----------------------------------

QueryFailedError: Field 'post_name' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

-----------------------------------/create_post 2024/3/5 12:26:8-----------------------------------

QueryFailedError: Field 'post_name' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

-----------------------------------/create_post 2024/3/5 12:33:19-----------------------------------

QueryFailedError: Field 'post_name' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

-----------------------------------/create_post 2024/3/5 12:34:0-----------------------------------

QueryFailedError: Field 'post_name' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

-----------------------------------/create_post 2024/3/5 12:34:35-----------------------------------

QueryFailedError: Field 'post_name' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

-----------------------------------/create_post 2024/3/5 13:4:24-----------------------------------

QueryFailedError: Field 'post_name' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

-----------------------------------/create_post 2024/3/5 15:42:10-----------------------------------

QueryFailedError: Field 'post_name' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

-----------------------------------/create_post 2024/3/5 15:44:3-----------------------------------

QueryFailedError: Field 'post_name' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

-----------------------------------/create_post 2024/3/5 15:44:31-----------------------------------

QueryFailedError: Field 'post_name' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

-----------------------------------/create_post 2024/3/5 15:44:48-----------------------------------

QueryFailedError: Field 'post_name' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

-----------------------------------/create_post 2024/3/5 15:45:27-----------------------------------

QueryFailedError: Field 'post_name' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

-----------------------------------/create_post 2024/3/5 15:46:2-----------------------------------

QueryFailedError: Field 'post_name' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

-----------------------------------/get_article 2024/3/0 10:16:41-----------------------------------

QueryFailedError: Table 'plateshare.article' doesn't exist
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

------------------------------------/get_post 2024/3/0 10:16:50------------------------------------

QueryFailedError: Table 'plateshare.post' doesn't exist
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

----------------------------------/create_event 2024/3/0 10:34:10----------------------------------

QueryFailedError: Data truncated for column 'event_time' at row 1
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

----------------------------------/create_event 2024/3/0 10:34:36----------------------------------

QueryFailedError: Incorrect integer value: 'adsda' for column `plateshare`.`event`.`event_time` at row 1
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

------------------------------------/put_menu 2024/3/0 10:57:46------------------------------------

TypeError: Cannot set properties of null (setting 'menu_type')
    at menuService.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:33:24)
    at step (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:33:23)
    at Object.next (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:14:53)
    at fulfilled (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

----------------------------------------------------------------------------------------------------

------------------------------------/put_menu 2024/3/0 10:58:26------------------------------------

TypeError: Cannot set properties of null (setting 'menu_type')
    at menuService.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:33:24)
    at step (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:33:23)
    at Object.next (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:14:53)
    at fulfilled (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

----------------------------------------------------------------------------------------------------

------------------------------------/register/ 2024/3/0 10:59:57------------------------------------

QueryFailedError: Field 'User_Role' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

------------------------------------/register/ 2024/3/0 11:0:44------------------------------------

QueryFailedError: Field 'User_Role' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

----------------------------------/create_order 2024/3/0 13:38:43----------------------------------

QueryFailedError: Field 'order_type' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

----------------------------------/create_order 2024/3/0 13:39:51----------------------------------

QueryFailedError: Field 'order_type' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

-----------------------------------/create_order 2024/3/0 14:8:4-----------------------------------

QueryFailedError: Field 'order_name' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

-----------------------------------/create_order 2024/3/0 14:8:41-----------------------------------

QueryFailedError: Field 'order_name' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

------------------------------------/put_menu 2024/3/0 14:29:49------------------------------------

TypeError: Cannot set properties of null (setting 'menu_type')
    at menuService.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:32:24)
    at step (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:33:23)
    at Object.next (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:14:53)
    at fulfilled (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

----------------------------------------------------------------------------------------------------

------------------------------------/put_menu 2024/3/0 14:31:24------------------------------------

TypeError: Cannot set properties of null (setting 'menu_type')
    at menuService.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:32:24)
    at step (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:33:23)
    at Object.next (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:14:53)
    at fulfilled (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

----------------------------------------------------------------------------------------------------

------------------------------------/put_menu 2024/3/0 14:33:43------------------------------------

TypeError: Cannot set properties of null (setting 'menu_type')
    at menuService.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:32:24)
    at step (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:33:23)
    at Object.next (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:14:53)
    at fulfilled (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

----------------------------------------------------------------------------------------------------

-------------------------------------/put_menu 2024/3/0 14:34:5-------------------------------------

TypeError: Cannot set properties of null (setting 'menu_type')
    at menuService.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:32:24)
    at step (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:33:23)
    at Object.next (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:14:53)
    at fulfilled (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

----------------------------------------------------------------------------------------------------

-------------------------------------/put_menu 2024/3/0 14:34:5-------------------------------------

TypeError: Cannot set properties of null (setting 'menu_type')
    at menuService.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:32:24)
    at step (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:33:23)
    at Object.next (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:14:53)
    at fulfilled (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

----------------------------------------------------------------------------------------------------

------------------------------------/put_menu 2024/3/0 14:34:11------------------------------------

TypeError: Cannot set properties of null (setting 'menu_type')
    at menuService.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:32:24)
    at step (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:33:23)
    at Object.next (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:14:53)
    at fulfilled (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

----------------------------------------------------------------------------------------------------

------------------------------------/put_menu 2024/3/0 14:34:28------------------------------------

TypeError: Cannot set properties of null (setting 'menu_type')
    at menuService.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:32:24)
    at step (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:33:23)
    at Object.next (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:14:53)
    at fulfilled (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/menu/Menu.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

----------------------------------------------------------------------------------------------------

------------------------------------/put_menu 2024/3/0 17:31:18------------------------------------

QueryFailedError: Incorrect integer value: 'undefined' for column `plateshare`.`menu`.`menu_price` at row 1
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

------------------------------------/put_menu 2024/3/0 17:31:31------------------------------------

QueryFailedError: Incorrect integer value: 'undefined' for column `plateshare`.`menu`.`menu_price` at row 1
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

------------------------------------/put_menu 2024/3/0 17:32:24------------------------------------

QueryFailedError: Incorrect integer value: 'undefined' for column `plateshare`.`menu`.`menu_price` at row 1
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

----------------------------------/create_donate 2024/3/0 18:35:12----------------------------------

QueryFailedError: Unknown column 'NaN' in 'field list'
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

----------------------------------/create_donate 2024/3/0 18:35:21----------------------------------

QueryFailedError: Unknown column 'NaN' in 'field list'
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

----------------------------------/create_donate 2024/3/0 18:37:41----------------------------------

QueryFailedError: Unknown column 'NaN' in 'field list'
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

----------------------------------/create_donate 2024/3/0 18:38:40----------------------------------

QueryFailedError: Unknown column 'NaN' in 'field list'
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

----------------------------------/create_donate 2024/3/0 18:41:8----------------------------------

QueryFailedError: Unknown column 'NaN' in 'field list'
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

----------------------------------/create_donate 2024/3/0 18:41:41----------------------------------

QueryFailedError: Unknown column 'NaN' in 'field list'
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

----------------------------------/create_donate 2024/3/0 20:10:15----------------------------------

QueryFailedError: Field 'donate_name' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

----------------------------------/create_donate 2024/3/0 22:16:48----------------------------------

QueryFailedError: Field 'donate_name' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

----------------------------------/create_donate 2024/3/0 22:17:25----------------------------------

QueryFailedError: Field 'donate_name' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

----------------------------------/create_donate 2024/3/0 22:17:55----------------------------------

QueryFailedError: Field 'donate_name' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

----------------------------------/create_donate 2024/3/0 22:20:52----------------------------------

QueryFailedError: Field 'donate_name' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

----------------------------------/create_donate 2024/3/0 22:21:56----------------------------------

QueryFailedError: Field 'donation_location' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

----------------------------------/create_donate 2024/3/0 22:23:20----------------------------------

QueryFailedError: Field 'donation_location' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

----------------------------------/create_donate 2024/3/1 0:33:35----------------------------------

QueryFailedError: Field 'donation_location' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

----------------------------------/create_donate 2024/3/1 0:48:23----------------------------------

QueryFailedError: Field 'donate_name' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

----------------------------------/create_donate 2024/3/1 0:55:45----------------------------------

QueryFailedError: Field 'donate_name' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

----------------------------------/create_donate 2024/3/1 0:56:30----------------------------------

QueryFailedError: Field 'donate_name' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

----------------------------------/create_donate 2024/3/1 0:56:48----------------------------------

QueryFailedError: Field 'donate_name' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

----------------------------------/create_order 2024/3/1 13:50:39----------------------------------

QueryFailedError: Field 'order_name' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

----------------------------------/create_order 2024/3/1 14:59:44----------------------------------

TypeError: parameterValue.value is not iterable
    at SelectQueryBuilder.getWherePredicateCondition (/Users/sarbagyashahi/fyp/plateshare/Backend/src/query-builder/QueryBuilder.ts:1516:52)
    at SelectQueryBuilder.buildWhere (/Users/sarbagyashahi/fyp/plateshare/Backend/src/query-builder/SelectQueryBuilder.ts:4317:34)
    at SelectQueryBuilder.applyFindOptions (/Users/sarbagyashahi/fyp/plateshare/Backend/src/query-builder/SelectQueryBuilder.ts:3141:40)
    at SelectQueryBuilder.setFindOptions (/Users/sarbagyashahi/fyp/plateshare/Backend/src/query-builder/SelectQueryBuilder.ts:105:14)
    at EntityManager.find (/Users/sarbagyashahi/fyp/plateshare/Backend/src/entity-manager/EntityManager.ts:1104:14)
    at Repository.find (/Users/sarbagyashahi/fyp/plateshare/Backend/src/repository/Repository.ts:544:29)
    at menuModel.GlobalModel.find (/Users/sarbagyashahi/fyp/plateshare/Backend/src/model/global.model.ts:22:26)
    at OrderService.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/Order/Order.service.ts:18:44)
    at step (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/Order/Order.service.ts:33:23)
    at Object.next (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/Order/Order.service.ts:14:53)

----------------------------------------------------------------------------------------------------

-----------------------------------/create_order 2024/3/1 15:0:49-----------------------------------

TypeError: parameterValue.value is not iterable
    at SelectQueryBuilder.getWherePredicateCondition (/Users/sarbagyashahi/fyp/plateshare/Backend/src/query-builder/QueryBuilder.ts:1516:52)
    at SelectQueryBuilder.buildWhere (/Users/sarbagyashahi/fyp/plateshare/Backend/src/query-builder/SelectQueryBuilder.ts:4317:34)
    at SelectQueryBuilder.applyFindOptions (/Users/sarbagyashahi/fyp/plateshare/Backend/src/query-builder/SelectQueryBuilder.ts:3141:40)
    at SelectQueryBuilder.setFindOptions (/Users/sarbagyashahi/fyp/plateshare/Backend/src/query-builder/SelectQueryBuilder.ts:105:14)
    at EntityManager.find (/Users/sarbagyashahi/fyp/plateshare/Backend/src/entity-manager/EntityManager.ts:1104:14)
    at Repository.find (/Users/sarbagyashahi/fyp/plateshare/Backend/src/repository/Repository.ts:544:29)
    at menuModel.GlobalModel.find (/Users/sarbagyashahi/fyp/plateshare/Backend/src/model/global.model.ts:22:26)
    at OrderService.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/Order/Order.service.ts:18:44)
    at step (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/Order/Order.service.ts:33:23)
    at Object.next (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/Order/Order.service.ts:14:53)

----------------------------------------------------------------------------------------------------

-----------------------------------/create_order 2024/3/1 15:1:32-----------------------------------

TypeError: parameterValue.value is not iterable
    at SelectQueryBuilder.getWherePredicateCondition (/Users/sarbagyashahi/fyp/plateshare/Backend/src/query-builder/QueryBuilder.ts:1516:52)
    at SelectQueryBuilder.buildWhere (/Users/sarbagyashahi/fyp/plateshare/Backend/src/query-builder/SelectQueryBuilder.ts:4317:34)
    at SelectQueryBuilder.applyFindOptions (/Users/sarbagyashahi/fyp/plateshare/Backend/src/query-builder/SelectQueryBuilder.ts:3141:40)
    at SelectQueryBuilder.setFindOptions (/Users/sarbagyashahi/fyp/plateshare/Backend/src/query-builder/SelectQueryBuilder.ts:105:14)
    at EntityManager.find (/Users/sarbagyashahi/fyp/plateshare/Backend/src/entity-manager/EntityManager.ts:1104:14)
    at Repository.find (/Users/sarbagyashahi/fyp/plateshare/Backend/src/repository/Repository.ts:544:29)
    at menuModel.GlobalModel.find (/Users/sarbagyashahi/fyp/plateshare/Backend/src/model/global.model.ts:22:26)
    at OrderService.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/Order/Order.service.ts:18:44)
    at step (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/Order/Order.service.ts:33:23)
    at Object.next (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/Order/Order.service.ts:14:53)

----------------------------------------------------------------------------------------------------

-----------------------------------/create_order 2024/3/1 15:2:7-----------------------------------

QueryFailedError: Field 'order_name' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

-----------------------------------/create_order 2024/3/1 15:2:25-----------------------------------

QueryFailedError: Field 'order_name' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

-----------------------------------/create_order 2024/3/1 15:2:43-----------------------------------

QueryFailedError: Field 'order_location' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

-----------------------------------/create_donate 2024/3/2 5:27:8-----------------------------------

QueryFailedError: Data truncated for column 'donated_time' at row 1
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

----------------------------------/create_article 2024/3/2 14:5:19----------------------------------

Error: MimeType or size doesn't match
    at new FileSizeExceed (/Users/sarbagyashahi/fyp/plateshare/Backend/src/middleware/error.middleware.ts:57:14)
    at FileStream.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/src/lib/imageHandler.ts:103:43)
    at FileStream.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

----------------------------------------------------------------------------------------------------

---------------------------------/create_article 2024/3/2 14:10:25---------------------------------

Error: MimeType or size doesn't match
    at new FileSizeExceed (/Users/sarbagyashahi/fyp/plateshare/Backend/src/middleware/error.middleware.ts:57:14)
    at FileStream.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/src/lib/imageHandler.ts:103:43)
    at FileStream.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

----------------------------------------------------------------------------------------------------

---------------------------------/create_article 2024/3/2 14:14:45---------------------------------

QueryFailedError: Field 'article_file' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

---------------------------------/create_article 2024/3/2 14:19:35---------------------------------

TypeError: Cannot read properties of undefined (reading '0')
    at articleController.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/Article/article.controller.ts:20:36)
    at step (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/Article/article.controller.ts:42:23)
    at Object.next (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/Article/article.controller.ts:23:53)
    at /Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/Article/article.controller.ts:17:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/Article/article.controller.ts:13:12)
    at articleController.create (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/Article/article.controller.ts:60:16)
    at articleController.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/src/lib/imageHandler.ts:218:42)
    at step (/Users/sarbagyashahi/fyp/plateshare/Backend/src/lib/imageHandler.ts:65:23)
    at Object.next (/Users/sarbagyashahi/fyp/plateshare/Backend/src/lib/imageHandler.ts:46:53)

----------------------------------------------------------------------------------------------------

---------------------------------/create_article 2024/3/2 14:26:29---------------------------------

TypeError: Cannot read properties of undefined (reading 'toString')
    at articleService.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/Article/article.service.ts:17:60)
    at step (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/Article/article.service.ts:56:23)
    at Object.next (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/Article/article.service.ts:37:53)
    at /Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/Article/article.service.ts:31:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/Article/article.service.ts:27:12)
    at articleService.createarticle (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/Article/article.service.ts:74:16)
    at articleController.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/Article/article.controller.ts:21:34)
    at step (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/Article/article.controller.ts:42:23)
    at Object.next (/Users/sarbagyashahi/fyp/plateshare/Backend/src/routes/Article/article.controller.ts:23:53)

----------------------------------------------------------------------------------------------------

-----------------------------------/create_post 2024/3/2 15:47:34-----------------------------------

Error: MimeType or size doesn't match
    at new FileSizeExceed (/Users/sarbagyashahi/fyp/plateshare/Backend/src/middleware/error.middleware.ts:57:14)
    at FileStream.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/src/lib/imageHandler.ts:157:43)
    at FileStream.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

----------------------------------------------------------------------------------------------------

-----------------------------------/create_post 2024/3/2 16:4:59-----------------------------------

QueryFailedError: Field 'post_name' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

-----------------------------------/create_post 2024/3/2 16:5:14-----------------------------------

QueryFailedError: Field 'post_name' doesn't have a default value
    at Query.onResult (/Users/sarbagyashahi/fyp/plateshare/Backend/src/driver/mysql/MysqlQueryRunner.ts:246:33)
    at Query.execute (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sarbagyashahi/fyp/plateshare/Backend/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)

----------------------------------------------------------------------------------------------------

------------------------------------/get_post 2025/2/1 15:54:39------------------------------------

EntityMetadataNotFoundError: No metadata for "post" was found.
    at DataSource.getMetadata (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\data-source\DataSource.ts:450:30)
    at Repository.get metadata [as metadata] (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\repository\Repository.ts:53:40)
    at Repository.find (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\repository\Repository.ts:544:39)
    at postModel.GlobalModel.find (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\model\global.model.ts:22:26)
    at postService.<anonymous> (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\post\post.service.ts:23:43)
    at step (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\post\post.service.ts:33:23)
    at Object.next (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\post\post.service.ts:14:53)
    at C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\post\post.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\post\post.service.ts:4:12)

----------------------------------------------------------------------------------------------------

------------------------------------/get_menu 2025/2/1 15:54:55------------------------------------

EntityMetadataNotFoundError: No metadata for "menu" was found.
    at DataSource.getMetadata (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\data-source\DataSource.ts:450:30)
    at Repository.get metadata [as metadata] (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\repository\Repository.ts:53:40)
    at Repository.find (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\repository\Repository.ts:544:39)
    at menuModel.GlobalModel.find (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\model\global.model.ts:22:26)
    at menuService.<anonymous> (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\menu\Menu.service.ts:26:43)
    at step (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\menu\Menu.service.ts:33:23)
    at Object.next (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\menu\Menu.service.ts:14:53)
    at C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\menu\Menu.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\menu\Menu.service.ts:4:12)

----------------------------------------------------------------------------------------------------

------------------------------------/register/ 2025/2/1 16:31:18------------------------------------

EntityMetadataNotFoundError: No metadata for "User" was found.
    at DataSource.getMetadata (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\data-source\DataSource.ts:450:30)
    at Repository.get metadata [as metadata] (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\repository\Repository.ts:53:40)
    at Repository.findOne (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\repository\Repository.ts:597:42)
    at UserModel.GlobalModel.findOne (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\model\global.model.ts:26:26)
    at AuthService.<anonymous> (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\auth\authservice.ts:20:50)
    at step (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\auth\authservice.ts:33:23)
    at Object.next (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\auth\authservice.ts:14:53)
    at C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\auth\authservice.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\auth\authservice.ts:4:12)

----------------------------------------------------------------------------------------------------

------------------------------------/register/ 2025/2/1 16:31:31------------------------------------

EntityMetadataNotFoundError: No metadata for "User" was found.
    at DataSource.getMetadata (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\data-source\DataSource.ts:450:30)
    at Repository.get metadata [as metadata] (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\repository\Repository.ts:53:40)
    at Repository.findOne (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\repository\Repository.ts:597:42)
    at UserModel.GlobalModel.findOne (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\model\global.model.ts:26:26)
    at AuthService.<anonymous> (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\auth\authservice.ts:20:50)
    at step (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\auth\authservice.ts:33:23)
    at Object.next (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\auth\authservice.ts:14:53)
    at C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\auth\authservice.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\auth\authservice.ts:4:12)

----------------------------------------------------------------------------------------------------

------------------------------------/register/ 2025/2/1 16:36:5------------------------------------

EntityMetadataNotFoundError: No metadata for "User" was found.
    at DataSource.getMetadata (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\data-source\DataSource.ts:450:30)
    at Repository.get metadata [as metadata] (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\repository\Repository.ts:53:40)
    at Repository.findOne (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\repository\Repository.ts:597:42)
    at UserModel.GlobalModel.findOne (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\model\global.model.ts:26:26)
    at AuthService.<anonymous> (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\auth\authservice.ts:20:50)
    at step (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\auth\authservice.ts:33:23)
    at Object.next (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\auth\authservice.ts:14:53)
    at C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\auth\authservice.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\auth\authservice.ts:4:12)

----------------------------------------------------------------------------------------------------

------------------------------------/register/ 2025/2/1 16:38:24------------------------------------

EntityMetadataNotFoundError: No metadata for "User" was found.
    at DataSource.getMetadata (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\data-source\DataSource.ts:450:30)
    at Repository.get metadata [as metadata] (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\repository\Repository.ts:53:40)
    at Repository.findOne (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\repository\Repository.ts:597:42)
    at UserModel.GlobalModel.findOne (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\model\global.model.ts:26:26)
    at AuthService.<anonymous> (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\auth\authservice.ts:20:50)
    at step (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\auth\authservice.ts:33:23)
    at Object.next (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\auth\authservice.ts:14:53)
    at C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\auth\authservice.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\auth\authservice.ts:4:12)

----------------------------------------------------------------------------------------------------

------------------------------------/register/ 2025/2/1 16:38:29------------------------------------

EntityMetadataNotFoundError: No metadata for "User" was found.
    at DataSource.getMetadata (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\data-source\DataSource.ts:450:30)
    at Repository.get metadata [as metadata] (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\repository\Repository.ts:53:40)
    at Repository.findOne (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\repository\Repository.ts:597:42)
    at UserModel.GlobalModel.findOne (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\model\global.model.ts:26:26)
    at AuthService.<anonymous> (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\auth\authservice.ts:20:50)
    at step (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\auth\authservice.ts:33:23)
    at Object.next (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\auth\authservice.ts:14:53)
    at C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\auth\authservice.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\auth\authservice.ts:4:12)

----------------------------------------------------------------------------------------------------

-------------------------------------/get_menu 2025/2/1 21:4:4-------------------------------------

EntityMetadataNotFoundError: No metadata for "menu" was found.
    at DataSource.getMetadata (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\data-source\DataSource.ts:450:30)
    at Repository.get metadata [as metadata] (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\repository\Repository.ts:53:40)
    at Repository.find (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\repository\Repository.ts:544:39)
    at menuModel.GlobalModel.find (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\model\global.model.ts:22:26)
    at menuService.<anonymous> (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\menu\Menu.service.ts:26:43)
    at step (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\menu\Menu.service.ts:33:23)
    at Object.next (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\menu\Menu.service.ts:14:53)
    at C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\menu\Menu.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\menu\Menu.service.ts:4:12)

----------------------------------------------------------------------------------------------------

-------------------------------------/get_post 2025/2/1 21:4:17-------------------------------------

EntityMetadataNotFoundError: No metadata for "post" was found.
    at DataSource.getMetadata (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\data-source\DataSource.ts:450:30)
    at Repository.get metadata [as metadata] (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\repository\Repository.ts:53:40)
    at Repository.find (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\repository\Repository.ts:544:39)
    at postModel.GlobalModel.find (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\model\global.model.ts:22:26)
    at postService.<anonymous> (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\post\post.service.ts:23:43)
    at step (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\post\post.service.ts:33:23)
    at Object.next (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\post\post.service.ts:14:53)
    at C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\post\post.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\post\post.service.ts:4:12)

----------------------------------------------------------------------------------------------------

------------------------------------/get_order 2025/2/1 21:4:44------------------------------------

EntityMetadataNotFoundError: No metadata for "order" was found.
    at DataSource.getMetadata (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\data-source\DataSource.ts:450:30)
    at Repository.get metadata [as metadata] (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\repository\Repository.ts:53:40)
    at Repository.find (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\repository\Repository.ts:544:39)
    at orderModel.GlobalModel.find (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\model\global.model.ts:22:26)
    at OrderService.<anonymous> (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\Order\Order.service.ts:32:45)
    at step (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\Order\Order.service.ts:33:23)
    at Object.next (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\Order\Order.service.ts:14:53)
    at C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\Order\Order.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\Order\Order.service.ts:4:12)

----------------------------------------------------------------------------------------------------

-------------------------------------/get_menu 2025/2/1 21:4:49-------------------------------------

EntityMetadataNotFoundError: No metadata for "menu" was found.
    at DataSource.getMetadata (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\data-source\DataSource.ts:450:30)
    at Repository.get metadata [as metadata] (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\repository\Repository.ts:53:40)
    at Repository.find (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\repository\Repository.ts:544:39)
    at menuModel.GlobalModel.find (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\model\global.model.ts:22:26)
    at menuService.<anonymous> (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\menu\Menu.service.ts:26:43)
    at step (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\menu\Menu.service.ts:33:23)
    at Object.next (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\menu\Menu.service.ts:14:53)
    at C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\menu\Menu.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\menu\Menu.service.ts:4:12)

----------------------------------------------------------------------------------------------------

------------------------------------/get_donate 2025/2/1 21:4:53------------------------------------

EntityMetadataNotFoundError: No metadata for "donate" was found.
    at DataSource.getMetadata (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\data-source\DataSource.ts:450:30)
    at Repository.get metadata [as metadata] (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\repository\Repository.ts:53:40)
    at Repository.find (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\repository\Repository.ts:544:39)
    at donateModel.GlobalModel.find (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\model\global.model.ts:22:26)
    at donateService.<anonymous> (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\Donate\Donate.service.ts:24:48)
    at step (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\Donate\Donate.service.ts:33:23)
    at Object.next (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\Donate\Donate.service.ts:14:53)
    at C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\Donate\Donate.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\Donate\Donate.service.ts:4:12)

----------------------------------------------------------------------------------------------------

------------------------------------/get_menu 2025/2/1 12:54:12------------------------------------

EntityMetadataNotFoundError: No metadata for "menu" was found.
    at DataSource.getMetadata (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\data-source\DataSource.ts:450:30)
    at Repository.get metadata [as metadata] (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\repository\Repository.ts:53:40)
    at Repository.find (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\repository\Repository.ts:544:39)
    at menuModel.GlobalModel.find (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\model\global.model.ts:22:26)
    at menuService.<anonymous> (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\menu\Menu.service.ts:26:43)
    at step (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\menu\Menu.service.ts:33:23)
    at Object.next (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\menu\Menu.service.ts:14:53)
    at C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\menu\Menu.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\menu\Menu.service.ts:4:12)

----------------------------------------------------------------------------------------------------

------------------------------------/get_menu 2025/2/1 12:58:58------------------------------------

EntityMetadataNotFoundError: No metadata for "menu" was found.
    at DataSource.getMetadata (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\data-source\DataSource.ts:450:30)
    at Repository.get metadata [as metadata] (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\repository\Repository.ts:53:40)
    at Repository.find (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\repository\Repository.ts:544:39)
    at menuModel.GlobalModel.find (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\model\global.model.ts:22:26)
    at menuService.<anonymous> (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\menu\Menu.service.ts:26:43)
    at step (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\menu\Menu.service.ts:33:23)
    at Object.next (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\menu\Menu.service.ts:14:53)
    at C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\menu\Menu.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\menu\Menu.service.ts:4:12)

----------------------------------------------------------------------------------------------------

------------------------------------/get_post 2025/2/1 12:59:11------------------------------------

EntityMetadataNotFoundError: No metadata for "post" was found.
    at DataSource.getMetadata (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\data-source\DataSource.ts:450:30)
    at Repository.get metadata [as metadata] (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\repository\Repository.ts:53:40)
    at Repository.find (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\repository\Repository.ts:544:39)
    at postModel.GlobalModel.find (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\model\global.model.ts:22:26)
    at postService.<anonymous> (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\post\post.service.ts:23:43)
    at step (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\post\post.service.ts:33:23)
    at Object.next (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\post\post.service.ts:14:53)
    at C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\post\post.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\FYP FOLDER\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Project Folder - [Plateshare]\Plateshare\plateshare\Backend\src\routes\post\post.service.ts:4:12)

----------------------------------------------------------------------------------------------------

-----------------------------------/get_article 2025/3/3 11:8:46-----------------------------------

EntityMetadataNotFoundError: No metadata for "article" was found.
    at DataSource.getMetadata (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\data-source\DataSource.ts:450:30)
    at Repository.get metadata [as metadata] (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\repository\Repository.ts:53:40)
    at Repository.find (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\repository\Repository.ts:544:39)
    at articleModel.GlobalModel.find (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\model\global.model.ts:22:26)
    at articleService.<anonymous> (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.service.ts:22:49)
    at step (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.service.ts:66:23)
    at Object.next (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.service.ts:47:53)
    at C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.service.ts:41:71
    at new Promise (<anonymous>)
    at __awaiter (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.service.ts:37:12)

----------------------------------------------------------------------------------------------------

-----------------------------------/get_article 2025/3/3 11:8:58-----------------------------------

EntityMetadataNotFoundError: No metadata for "article" was found.
    at DataSource.getMetadata (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\data-source\DataSource.ts:450:30)
    at Repository.get metadata [as metadata] (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\repository\Repository.ts:53:40)
    at Repository.find (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\repository\Repository.ts:544:39)
    at articleModel.GlobalModel.find (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\model\global.model.ts:22:26)
    at articleService.<anonymous> (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.service.ts:22:49)
    at step (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.service.ts:66:23)
    at Object.next (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.service.ts:47:53)
    at C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.service.ts:41:71
    at new Promise (<anonymous>)
    at __awaiter (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.service.ts:37:12)

----------------------------------------------------------------------------------------------------

-----------------------------------/get_article 2025/3/3 11:11:9-----------------------------------

EntityMetadataNotFoundError: No metadata for "article" was found.
    at DataSource.getMetadata (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\data-source\DataSource.ts:450:30)
    at Repository.get metadata [as metadata] (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\repository\Repository.ts:53:40)
    at Repository.find (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\repository\Repository.ts:544:39)
    at articleModel.GlobalModel.find (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\model\global.model.ts:22:26)
    at articleService.<anonymous> (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.service.ts:22:49)
    at step (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.service.ts:66:23)
    at Object.next (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.service.ts:47:53)
    at C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.service.ts:41:71
    at new Promise (<anonymous>)
    at __awaiter (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.service.ts:37:12)

----------------------------------------------------------------------------------------------------

-----------------------------------/get_article 2025/3/3 11:13:36-----------------------------------

EntityMetadataNotFoundError: No metadata for "article" was found.
    at DataSource.getMetadata (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\data-source\DataSource.ts:450:30)
    at Repository.get metadata [as metadata] (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\repository\Repository.ts:53:40)
    at Repository.find (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\repository\Repository.ts:544:39)
    at articleModel.GlobalModel.find (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\model\global.model.ts:22:26)
    at articleService.<anonymous> (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.service.ts:22:49)
    at step (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.service.ts:66:23)
    at Object.next (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.service.ts:47:53)
    at C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.service.ts:41:71
    at new Promise (<anonymous>)
    at __awaiter (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.service.ts:37:12)

----------------------------------------------------------------------------------------------------

-----------------------------------/get_article 2025/3/3 11:15:38-----------------------------------

EntityMetadataNotFoundError: No metadata for "article" was found.
    at DataSource.getMetadata (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\data-source\DataSource.ts:450:30)
    at Repository.get metadata [as metadata] (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\repository\Repository.ts:53:40)
    at Repository.find (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\repository\Repository.ts:544:39)
    at articleModel.GlobalModel.find (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\model\global.model.ts:22:26)
    at articleService.<anonymous> (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.service.ts:22:49)
    at step (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.service.ts:66:23)
    at Object.next (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.service.ts:47:53)
    at C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.service.ts:41:71
    at new Promise (<anonymous>)
    at __awaiter (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.service.ts:37:12)

----------------------------------------------------------------------------------------------------

-----------------------------------/get_article 2025/3/3 11:19:8-----------------------------------

EntityMetadataNotFoundError: No metadata for "article" was found.
    at DataSource.getMetadata (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\data-source\DataSource.ts:450:30)
    at Repository.get metadata [as metadata] (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\repository\Repository.ts:53:40)
    at Repository.find (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\repository\Repository.ts:544:39)
    at articleModel.GlobalModel.find (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\model\global.model.ts:22:26)
    at articleService.<anonymous> (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.service.ts:22:49)
    at step (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.service.ts:66:23)
    at Object.next (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.service.ts:47:53)
    at C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.service.ts:41:71
    at new Promise (<anonymous>)
    at __awaiter (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.service.ts:37:12)

----------------------------------------------------------------------------------------------------

---------------------------------/create_article 2025/3/3 21:57:10---------------------------------

Error: MimeType or size doesn't match
    at new FileSizeExceed (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\middleware\error.middleware.ts:57:14)
    at FileStream.<anonymous> (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\lib\imageHandler.ts:103:43)
    at FileStream.emit (node:events:536:35)
    at endReadableNT (node:internal/streams/readable:1698:12)
    at processTicksAndRejections (node:internal/process/task_queues:90:21)

----------------------------------------------------------------------------------------------------

---------------------------------/create_article 2025/3/3 21:57:13---------------------------------

Error: MimeType or size doesn't match
    at new FileSizeExceed (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\middleware\error.middleware.ts:57:14)
    at FileStream.<anonymous> (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\lib\imageHandler.ts:103:43)
    at FileStream.emit (node:events:536:35)
    at endReadableNT (node:internal/streams/readable:1698:12)
    at processTicksAndRejections (node:internal/process/task_queues:90:21)

----------------------------------------------------------------------------------------------------

---------------------------------/create_article 2025/3/3 21:58:30---------------------------------

Error: MimeType or size doesn't match
    at new FileSizeExceed (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\middleware\error.middleware.ts:57:14)
    at FileStream.<anonymous> (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\lib\imageHandler.ts:103:43)
    at FileStream.emit (node:events:536:35)
    at endReadableNT (node:internal/streams/readable:1698:12)
    at processTicksAndRejections (node:internal/process/task_queues:90:21)

----------------------------------------------------------------------------------------------------

----------------------------------/create_article 2025/3/3 22:4:16----------------------------------

TypeError: Cannot read properties of undefined (reading '0')
    at articleController.<anonymous> (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.controller.ts:19:63)
    at step (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.controller.ts:42:23)
    at Object.next (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.controller.ts:23:53)
    at C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.controller.ts:17:71
    at new Promise (<anonymous>)
    at __awaiter (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.controller.ts:13:12)
    at articleController.create (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.controller.ts:60:16)
    at articleController.<anonymous> (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\lib\imageHandler.ts:218:42)
    at step (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\lib\imageHandler.ts:75:23)
    at Object.next (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\lib\imageHandler.ts:56:53)

----------------------------------------------------------------------------------------------------

----------------------------------/create_article 2025/3/3 22:5:41----------------------------------

TypeError: Cannot read properties of undefined (reading '0')
    at articleController.<anonymous> (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.controller.ts:19:63)
    at step (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.controller.ts:42:23)
    at Object.next (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.controller.ts:23:53)
    at C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.controller.ts:17:71
    at new Promise (<anonymous>)
    at __awaiter (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.controller.ts:13:12)
    at articleController.create (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Article\article.controller.ts:60:16)
    at articleController.<anonymous> (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\lib\imageHandler.ts:218:42)
    at step (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\lib\imageHandler.ts:75:23)
    at Object.next (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\lib\imageHandler.ts:56:53)

----------------------------------------------------------------------------------------------------

-----------------------------------/get_donate 2025/3/3 22:53:58-----------------------------------

EntityMetadataNotFoundError: No metadata for "donate" was found.
    at DataSource.getMetadata (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\data-source\DataSource.ts:450:30)
    at Repository.get metadata [as metadata] (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\repository\Repository.ts:53:40)
    at Repository.find (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\repository\Repository.ts:544:39)
    at donateModel.GlobalModel.find (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\model\global.model.ts:22:26)
    at donateService.<anonymous> (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Donate\Donate.service.ts:24:48)
    at step (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Donate\Donate.service.ts:33:23)
    at Object.next (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Donate\Donate.service.ts:14:53)
    at C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Donate\Donate.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Donate\Donate.service.ts:4:12)

----------------------------------------------------------------------------------------------------

-----------------------------------/get_donate 2025/3/3 22:54:34-----------------------------------

EntityMetadataNotFoundError: No metadata for "donate" was found.
    at DataSource.getMetadata (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\data-source\DataSource.ts:450:30)
    at Repository.get metadata [as metadata] (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\repository\Repository.ts:53:40)
    at Repository.find (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\repository\Repository.ts:544:39)
    at donateModel.GlobalModel.find (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\model\global.model.ts:22:26)
    at donateService.<anonymous> (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Donate\Donate.service.ts:24:48)
    at step (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Donate\Donate.service.ts:33:23)
    at Object.next (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Donate\Donate.service.ts:14:53)
    at C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Donate\Donate.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Donate\Donate.service.ts:4:12)

----------------------------------------------------------------------------------------------------

-----------------------------------/get_donate 2025/3/3 22:55:39-----------------------------------

EntityMetadataNotFoundError: No metadata for "donate" was found.
    at DataSource.getMetadata (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\data-source\DataSource.ts:450:30)
    at Repository.get metadata [as metadata] (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\repository\Repository.ts:53:40)
    at Repository.find (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\repository\Repository.ts:544:39)
    at donateModel.GlobalModel.find (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\model\global.model.ts:22:26)
    at donateService.<anonymous> (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Donate\Donate.service.ts:24:48)
    at step (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Donate\Donate.service.ts:33:23)
    at Object.next (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Donate\Donate.service.ts:14:53)
    at C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Donate\Donate.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Donate\Donate.service.ts:4:12)

----------------------------------------------------------------------------------------------------

-----------------------------------/get_donate 2025/3/3 22:55:49-----------------------------------

EntityMetadataNotFoundError: No metadata for "donate" was found.
    at DataSource.getMetadata (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\data-source\DataSource.ts:450:30)
    at Repository.get metadata [as metadata] (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\repository\Repository.ts:53:40)
    at Repository.find (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\repository\Repository.ts:544:39)
    at donateModel.GlobalModel.find (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\model\global.model.ts:22:26)
    at donateService.<anonymous> (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Donate\Donate.service.ts:24:48)
    at step (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Donate\Donate.service.ts:33:23)
    at Object.next (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Donate\Donate.service.ts:14:53)
    at C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Donate\Donate.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Donate\Donate.service.ts:4:12)

----------------------------------------------------------------------------------------------------

-----------------------------------/get_donate 2025/3/3 22:56:40-----------------------------------

EntityMetadataNotFoundError: No metadata for "donate" was found.
    at DataSource.getMetadata (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\data-source\DataSource.ts:450:30)
    at Repository.get metadata [as metadata] (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\repository\Repository.ts:53:40)
    at Repository.find (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\repository\Repository.ts:544:39)
    at donateModel.GlobalModel.find (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\model\global.model.ts:22:26)
    at donateService.<anonymous> (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Donate\Donate.service.ts:24:48)
    at step (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Donate\Donate.service.ts:33:23)
    at Object.next (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Donate\Donate.service.ts:14:53)
    at C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Donate\Donate.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Donate\Donate.service.ts:4:12)

----------------------------------------------------------------------------------------------------

------------------------------------/get_event 2025/3/3 23:1:23------------------------------------

EntityMetadataNotFoundError: No metadata for "event" was found.
    at DataSource.getMetadata (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\data-source\DataSource.ts:450:30)
    at Repository.get metadata [as metadata] (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\repository\Repository.ts:53:40)
    at Repository.find (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\repository\Repository.ts:544:39)
    at eventModel.GlobalModel.find (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\model\global.model.ts:22:26)
    at eventService.<anonymous> (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Event\Event.service.ts:28:45)
    at step (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Event\Event.service.ts:33:23)
    at Object.next (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Event\Event.service.ts:14:53)
    at C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Event\Event.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Event\Event.service.ts:4:12)

----------------------------------------------------------------------------------------------------

------------------------------------/get_donate 2025/3/3 23:1:34------------------------------------

EntityMetadataNotFoundError: No metadata for "donate" was found.
    at DataSource.getMetadata (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\data-source\DataSource.ts:450:30)
    at Repository.get metadata [as metadata] (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\repository\Repository.ts:53:40)
    at Repository.find (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\repository\Repository.ts:544:39)
    at donateModel.GlobalModel.find (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\model\global.model.ts:22:26)
    at donateService.<anonymous> (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Donate\Donate.service.ts:24:48)
    at step (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Donate\Donate.service.ts:33:23)
    at Object.next (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Donate\Donate.service.ts:14:53)
    at C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Donate\Donate.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\FYP FOLDER\Project Folder - [OED]\Project Folder - [OED]\Project Folder - [OED]\OED\OED\Backend\src\routes\Donate\Donate.service.ts:4:12)

----------------------------------------------------------------------------------------------------

